const languages = {
    'ko': {
        'site_title': 'MAI MI IOTU - 인조 속눈썹 전문 기업',
        'nav_language': '언어',
        'nav_contact': '연락처',
        'home_title': 'MAI MI IOTU',
        'business_title': '주요 사업',
        'oem_title': '주문자 상표 위탁 생산 (OEM)',
        'oem_desc': 'MAI MI IOTU는 고객사의 브랜드로 고품질 인조 속눈썹을 생산하는 데 특화되어 있습니다. 다년간의 경험과 최신 설비를 바탕으로 고객의 요구사항에 맞는 최적의 제품을 제공합니다.',
        'brand_title': '자체 브랜드 인조 속눈썹',
        'brand_desc': 'MAI MI IOTU는 자체 브랜드의 인조 속눈썹 제품도 개발 및 생산하고 있습니다. 최신 트렌드를 반영한 혁신적인 디자인과 우수한 품질로 시장을 선도합니다.',
        'products_title': '주요 제품',
        'products_desc': '다양한 종류와 스타일의 인조 속눈썹을 만나보세요.',
        'product1_title': '클래식 래쉬',
        'product1_desc': '자연스럽고 선명한 눈매 연출',
        'product2_title': '볼륨 래쉬',
        'product2_desc': '풍성하고 화려한 눈매 연출',
        'product3_title': '특수 래쉬',
        'product3_desc': '독특하고 개성 있는 디자인',
        'product4_title': '컬러 래쉬',
        'product4_desc': '다양한 컬러로 특별한 포인트',
        'location_title': '공장 위치',
        'location_desc': 'MAI MI IOTU는 베트남 빈증에 위치하고 있습니다.',
        'address_label': '주소:',
        'contact_title': '연락처',
        'contact_desc': '궁금한 점이 있으시면 언제든지 문의해 주세요.',
        'rep_label': '대표:',
        'phone_label': '연락처:',
        'email_label': '이메일:',
        'footer_text': '© 2025 MAI MI IOTU. All Rights Reserved.'
    },
    'vi': {
        'site_title': 'MAI MI IOTU - Chuyên gia về lông mi giả',
        'nav_language': 'Ngôn ngữ',
        'nav_contact': 'Liên hệ',
        'home_title': 'MAI MI IOTU',
        'business_title': 'Kinh doanh chính',
        'oem_title': 'Sản xuất OEM',
        'oem_desc': 'MAI MI IOTU chuyên sản xuất lông mi giả chất lượng cao mang thương hiệu của khách hàng. Với kinh nghiệm nhiều năm và thiết bị hiện đại, chúng tôi cung cấp sản phẩm tối ưu đáp ứng yêu cầu.',
        'brand_title': 'Thương hiệu riêng',
        'brand_desc': 'MAI MI IOTU cũng phát triển và sản xuất các sản phẩm lông mi giả mang thương hiệu riêng. Chúng tôi dẫn đầu thị trường với thiết kế sáng tạo và chất lượng vượt trội.',
        'products_title': 'Sản phẩm chính',
        'products_desc': 'Khám phá các loại lông mi giả đa dạng.',
        'product1_title': 'Classic Lash',
        'product1_desc': 'Tạo đôi mắt tự nhiên và sắc nét',
        'product2_title': 'Volume Lash',
        'product2_desc': 'Tạo đôi mắt dày và lộng lẫy',
        'product3_title': 'Special Lash',
        'product3_desc': 'Thiết kế độc đáo và cá tính',
        'product4_title': 'Color Lash',
        'product4_desc': 'Điểm nhấn đặc biệt với nhiều màu sắc',
        'location_title': 'Vị trí nhà máy',
        'location_desc': 'MAI MI IOTU đặt tại Bình Dương, Việt Nam.',
        'address_label': 'Địa chỉ:',
        'contact_title': 'Liên hệ',
        'contact_desc': 'Nếu bạn có bất kỳ câu hỏi nào, xin vui lòng liên hệ.',
        'rep_label': 'Đại diện:',
        'phone_label': 'Điện thoại:',
        'email_label': 'Email:',
        'footer_text': '© 2025 MAI MI IOTU. Mọi quyền được bảo lưu.'
    },
    'en': {
        'site_title': 'MAI MI IOTU - Artificial Eyelash Specialist',
        'nav_language': 'Language',
        'nav_contact': 'Contact',
        'home_title': 'MAI MI IOTU',
        'business_title': 'Main Business',
        'oem_title': 'Original Equipment Manufacturing (OEM)',
        'oem_desc': 'MAI MI IOTU specializes in producing high-quality artificial eyelashes under our clients\' brands. With years of experience and modern facilities, we provide optimal products meeting customer requirements.',
        'brand_title': 'Own Brand Eyelashes',
        'brand_desc': 'MAI MI IOTU also develops and produces its own brand of artificial eyelash products. We lead the market with innovative designs and excellent quality reflecting the latest trends.',
        'products_title': 'Main Products',
        'products_desc': 'Discover various types and styles of artificial eyelashes.',
        'product1_title': 'Classic Lash',
        'product1_desc': 'For a natural and defined look',
        'product2_title': 'Volume Lash',
        'product2_desc': 'For a full and glamorous look',
        'product3_title': 'Special Lash',
        'product3_desc': 'Unique and individual designs',
        'product4_title': 'Color Lash',
        'product4_desc': 'Special highlights with various colors',
        'location_title': 'Factory Location',
        'location_desc': 'MAI MI IOTU is located in Binh Duong, Vietnam.',
        'address_label': 'Address:',
        'contact_title': 'Contact',
        'contact_desc': 'Please feel free to contact us if you have any questions.',
        'rep_label': 'Representative:',
        'phone_label': 'Contact:',
        'email_label': 'Email:',
        'footer_text': '© 2025 MAI MI IOTU. All Rights Reserved.'
    },
    'ja': {
        'site_title': 'MAI MI IOTU - 人工まつげ専門企業',
        'nav_language': '言語',
        'nav_contact': '問合せ',
        'home_title': 'MAI MI IOTU',
        'business_title': '主な事業',
        'oem_title': 'OEM生産',
        'oem_desc': 'MAI MI IOTUは、お客様のブランドで高品質な人工まつげを生産します。長年の経験と最新設備に基づき、最適な製品を提供します。',
        'brand_title': '自社ブランド',
        'brand_desc': 'MAI MI IOTUは自社ブランドの人工まつげも開発・生産しています。革新的なデザインと優れた品質で市場をリードします。',
        'products_title': '主な製品',
        'products_desc': '様々な種類の人工まつげをご覧ください。',
        'product1_title': 'クラシック',
        'product1_desc': '自然でくっきりとした目元を演出',
        'product2_title': 'ボリューム',
        'product2_desc': '豊かで華やかな目元を演出',
        'product3_title': 'スペシャル',
        'product3_desc': 'ユニークで個性的なデザイン',
        'product4_title': 'カラー',
        'product4_desc': '様々なカラーで特別なポイントを',
        'location_title': '工場の場所',
        'location_desc': 'MAI MI IOTUはベトナムのビンズオンにあります。',
        'address_label': '住所:',
        'contact_title': 'お問い合わせ',
        'contact_desc': 'ご不明な点がございましたら、お気軽にどうぞ。',
        'rep_label': '代表:',
        'phone_label': '連絡先:',
        'email_label': 'メール:',
        'footer_text': '© 2025 MAI MI IOTU. All Rights Reserved.'
    }
};
